// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ConversationItem is a conversation message for the detail view.
 */
export class ConversationItem {
    "role": string;
    "text": string;
    "timestamp": time$0.Time;

    /** Creates a new ConversationItem instance. */
    constructor($$source: Partial<ConversationItem> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationItem($$parsedSource as Partial<ConversationItem>);
    }
}

/**
 * SessionFull is the detailed session representation.
 */
export class SessionFull {
    "sessionId": string;
    "agent": string;
    "source": string;
    "cwd": string;
    "shortName": string;
    "customName": string;
    "activity": string;
    "isActive": boolean;
    "model": string;
    "gitBranch": string;
    "costUsd": number;
    "lastActivity": time$0.Time;
    "totalMessages": number;
    "sparklineData": number[];
    "version": string;
    "isWorktree": boolean;
    "mainRepo": string;
    "inputTokens": number;
    "outputTokens": number;
    "cacheCreationTokens": number;
    "cacheReadTokens": number;
    "userMessages": number;
    "assistantMessages": number;
    "currentTool": string;
    "lastFileWrite": string;
    "lastFileWriteAt": time$0.Time;
    "recentTools": ToolItem[];
    "recentMessages": ConversationItem[];
    "desktopTitle"?: string;
    "desktopId"?: string;
    "permissionMode"?: string;

    /** Creates a new SessionFull instance. */
    constructor($$source: Partial<SessionFull> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("customName" in $$source)) {
            this["customName"] = "";
        }
        if (!("activity" in $$source)) {
            this["activity"] = "";
        }
        if (!("isActive" in $$source)) {
            this["isActive"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("gitBranch" in $$source)) {
            this["gitBranch"] = "";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("lastActivity" in $$source)) {
            this["lastActivity"] = null;
        }
        if (!("totalMessages" in $$source)) {
            this["totalMessages"] = 0;
        }
        if (!("sparklineData" in $$source)) {
            this["sparklineData"] = [];
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("isWorktree" in $$source)) {
            this["isWorktree"] = false;
        }
        if (!("mainRepo" in $$source)) {
            this["mainRepo"] = "";
        }
        if (!("inputTokens" in $$source)) {
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = 0;
        }
        if (!("cacheCreationTokens" in $$source)) {
            this["cacheCreationTokens"] = 0;
        }
        if (!("cacheReadTokens" in $$source)) {
            this["cacheReadTokens"] = 0;
        }
        if (!("userMessages" in $$source)) {
            this["userMessages"] = 0;
        }
        if (!("assistantMessages" in $$source)) {
            this["assistantMessages"] = 0;
        }
        if (!("currentTool" in $$source)) {
            this["currentTool"] = "";
        }
        if (!("lastFileWrite" in $$source)) {
            this["lastFileWrite"] = "";
        }
        if (!("lastFileWriteAt" in $$source)) {
            this["lastFileWriteAt"] = null;
        }
        if (!("recentTools" in $$source)) {
            this["recentTools"] = [];
        }
        if (!("recentMessages" in $$source)) {
            this["recentMessages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFull instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionFull {
        const $$createField13_0 = $$createType0;
        const $$createField26_0 = $$createType2;
        const $$createField27_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sparklineData" in $$parsedSource) {
            $$parsedSource["sparklineData"] = $$createField13_0($$parsedSource["sparklineData"]);
        }
        if ("recentTools" in $$parsedSource) {
            $$parsedSource["recentTools"] = $$createField26_0($$parsedSource["recentTools"]);
        }
        if ("recentMessages" in $$parsedSource) {
            $$parsedSource["recentMessages"] = $$createField27_0($$parsedSource["recentMessages"]);
        }
        return new SessionFull($$parsedSource as Partial<SessionFull>);
    }
}

/**
 * SessionItem is a lightweight session representation for the list view.
 */
export class SessionItem {
    "sessionId": string;
    "agent": string;
    "source": string;
    "cwd": string;
    "shortName": string;
    "customName": string;
    "activity": string;
    "isActive": boolean;
    "model": string;
    "gitBranch": string;
    "costUsd": number;
    "lastActivity": time$0.Time;
    "totalMessages": number;
    "sparklineData": number[];

    /** Creates a new SessionItem instance. */
    constructor($$source: Partial<SessionItem> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("customName" in $$source)) {
            this["customName"] = "";
        }
        if (!("activity" in $$source)) {
            this["activity"] = "";
        }
        if (!("isActive" in $$source)) {
            this["isActive"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("gitBranch" in $$source)) {
            this["gitBranch"] = "";
        }
        if (!("costUsd" in $$source)) {
            this["costUsd"] = 0;
        }
        if (!("lastActivity" in $$source)) {
            this["lastActivity"] = null;
        }
        if (!("totalMessages" in $$source)) {
            this["totalMessages"] = 0;
        }
        if (!("sparklineData" in $$source)) {
            this["sparklineData"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionItem {
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sparklineData" in $$parsedSource) {
            $$parsedSource["sparklineData"] = $$createField13_0($$parsedSource["sparklineData"]);
        }
        return new SessionItem($$parsedSource as Partial<SessionItem>);
    }
}

/**
 * ToolItem is a tool call for the detail view.
 */
export class ToolItem {
    "name": string;
    "timestamp": time$0.Time;
    "ago": string;

    /** Creates a new ToolItem instance. */
    constructor($$source: Partial<ToolItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("ago" in $$source)) {
            this["ago"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolItem($$parsedSource as Partial<ToolItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ToolItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ConversationItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
