// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the Go service exposed to the Svelte frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetActiveCount returns the number of sessions with active work.
 */
export function GetActiveCount(): $CancellablePromise<number> {
    return $Call.ByID(4081026139);
}

/**
 * GetConfig returns the current config.
 */
export function GetConfig(): $CancellablePromise<core$0.Config> {
    return $Call.ByID(3325798956).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSessionDetail returns full detail for a session.
 */
export function GetSessionDetail(id: string): $CancellablePromise<$models.SessionFull | null> {
    return $Call.ByID(3865970311, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSessionName returns the custom name for a session.
 */
export function GetSessionName(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(3799911173, sessionID);
}

/**
 * GetSessions returns all visible sessions for the list view.
 */
export function GetSessions(): $CancellablePromise<$models.SessionItem[]> {
    return $Call.ByID(2715330479).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetWindowMinutes returns the current time window in minutes.
 */
export function GetWindowMinutes(): $CancellablePromise<number> {
    return $Call.ByID(623328891);
}

/**
 * OpenInEditor opens a directory in the user's editor.
 * For Cursor sessions, it opens Cursor IDE directly.
 * Otherwise it follows POSIX semantics: $VISUAL is a GUI editor (launched directly),
 * $EDITOR is a terminal editor (opened inside a Terminal.app window).
 * The config "editor" field is treated as VISUAL (GUI) for backward compatibility.
 */
export function OpenInEditor(cwd: string, agent: string): $CancellablePromise<void> {
    return $Call.ByID(1983870972, cwd, agent);
}

/**
 * SetActivityFilter sets the activity filter.
 */
export function SetActivityFilter(f: string): $CancellablePromise<void> {
    return $Call.ByID(3340685613, f);
}

/**
 * SetSearchQuery sets the search query.
 */
export function SetSearchQuery(q: string): $CancellablePromise<void> {
    return $Call.ByID(2439661330, q);
}

/**
 * SetSessionName stores a custom name for a session. Empty name resets it.
 */
export function SetSessionName(sessionID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(602820185, sessionID, name);
}

/**
 * SetWindowMinutes updates the time window.
 */
export function SetWindowMinutes(m: number): $CancellablePromise<void> {
    return $Call.ByID(2220190495, m);
}

// Private type creation functions
const $$createType0 = core$0.Config.createFrom;
const $$createType1 = $models.SessionFull.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.SessionItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
