// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the Go service exposed to the Svelte frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../internal/core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetActiveCount returns the number of sessions with active work.
 */
export function GetActiveCount(): $CancellablePromise<number> {
    return $Call.ByID(147928324);
}

/**
 * GetConfig returns the current config.
 */
export function GetConfig(): $CancellablePromise<core$0.Config> {
    return $Call.ByID(1166205385).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSessionDetail returns full detail for a session.
 */
export function GetSessionDetail(id: string): $CancellablePromise<$models.SessionFull | null> {
    return $Call.ByID(3921151444, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSessions returns all visible sessions for the list view.
 */
export function GetSessions(): $CancellablePromise<$models.SessionItem[]> {
    return $Call.ByID(474068578).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetWindowMinutes returns the current time window in minutes.
 */
export function GetWindowMinutes(): $CancellablePromise<number> {
    return $Call.ByID(2478459800);
}

/**
 * OpenInEditor opens a directory in the user's editor.
 */
export function OpenInEditor(cwd: string): $CancellablePromise<void> {
    return $Call.ByID(1075961887, cwd);
}

/**
 * SetActivityFilter sets the activity filter.
 */
export function SetActivityFilter(f: string): $CancellablePromise<void> {
    return $Call.ByID(2685849448, f);
}

/**
 * SetSearchQuery sets the search query.
 */
export function SetSearchQuery(q: string): $CancellablePromise<void> {
    return $Call.ByID(2127677093, q);
}

/**
 * SetWindowMinutes updates the time window.
 */
export function SetWindowMinutes(m: number): $CancellablePromise<void> {
    return $Call.ByID(3044962628, m);
}

// Private type creation functions
const $$createType0 = core$0.Config.createFrom;
const $$createType1 = $models.SessionFull.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.SessionItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
