// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds application settings shared by TUI and GUI.
 */
export class Config {
    "window_minutes": number;
    "default_filter": string;
    "editor": string;
    "launch_at_login": boolean;
    "notifications": boolean;
    "notify_after_sec": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("window_minutes" in $$source)) {
            this["window_minutes"] = 0;
        }
        if (!("default_filter" in $$source)) {
            this["default_filter"] = "";
        }
        if (!("editor" in $$source)) {
            this["editor"] = "";
        }
        if (!("launch_at_login" in $$source)) {
            this["launch_at_login"] = false;
        }
        if (!("notifications" in $$source)) {
            this["notifications"] = false;
        }
        if (!("notify_after_sec" in $$source)) {
            this["notify_after_sec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
