// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the Go service exposed to the Svelte frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as limits$0 from "../limits/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Attach switches from detached window back to tray panel mode.
 */
export function Attach(): $CancellablePromise<void> {
    return $Call.ByID(770700779);
}

/**
 * Detach switches from tray panel to a normal detached window.
 */
export function Detach(): $CancellablePromise<void> {
    return $Call.ByID(3825720405);
}

/**
 * GetAPIToken derives and returns the API bearer token. It exists for the
 * explicit "copy token" action in Settings; empty when unconfigured.
 */
export function GetAPIToken(): $CancellablePromise<string> {
    return $Call.ByID(1795248511);
}

/**
 * GetActiveCount returns the number of sessions with active work.
 */
export function GetActiveCount(): $CancellablePromise<number> {
    return $Call.ByID(1984306295);
}

/**
 * GetCardDensity returns the persisted desktop card density. Missing or
 * invalid values fall back to "live".
 */
export function GetCardDensity(): $CancellablePromise<string> {
    return $Call.ByID(2985488372);
}

/**
 * GetConfig returns the current config. The API passphrase is scrubbed
 * before returning so the secret never crosses the Wails IPC boundary into
 * the frontend (mirrors what /api/config does for HTTP callers).
 */
export function GetConfig(): $CancellablePromise<core$0.Config> {
    return $Call.ByID(1670992424).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDetailWidth returns the persisted desktop detail-panel width in
 * pixels. Missing or out-of-range values fall back to 400.
 */
export function GetDetailWidth(): $CancellablePromise<number> {
    return $Call.ByID(2792703953);
}

/**
 * GetLimits fetches all supported providers and returns the computed limits
 * view. The GUI calls it when the limits page opens and on manual refresh; it
 * does not poll. Missing/errored agents are omitted.
 */
export function GetLimits(): $CancellablePromise<limits$0.View> {
    return $Call.ByID(1368178874).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSessionDetail returns full detail for a session.
 */
export function GetSessionDetail(id: string): $CancellablePromise<$models.SessionFull | null> {
    return $Call.ByID(378650659, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSessionName returns the custom name for a session.
 */
export function GetSessionName(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(190900857, sessionID);
}

/**
 * GetSessions returns all visible sessions for the list view.
 */
export function GetSessions(): $CancellablePromise<$models.SessionItem[]> {
    return $Call.ByID(330309427).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSettings returns the GUI-editable settings.
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1562138763).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetUpdateVersion returns the newer version available, or empty if up-to-date.
 */
export function GetUpdateVersion(): $CancellablePromise<string> {
    return $Call.ByID(707030249);
}

/**
 * GetWindowMinutes returns the current time window in minutes.
 */
export function GetWindowMinutes(): $CancellablePromise<number> {
    return $Call.ByID(4178116159);
}

/**
 * IsAPIConfigured reports whether an API passphrase is set. The passphrase
 * itself never crosses the IPC boundary (GetConfig scrubs it).
 */
export function IsAPIConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(3199271690);
}

/**
 * IsDetached returns whether the app is currently in detached window mode.
 */
export function IsDetached(): $CancellablePromise<boolean> {
    return $Call.ByID(279822792);
}

/**
 * IsPinned returns whether the detached window is always on top.
 */
export function IsPinned(): $CancellablePromise<boolean> {
    return $Call.ByID(3827525600);
}

/**
 * OpenInEditor opens a directory in the user's editor.
 * For Cursor sessions, it opens Cursor IDE directly.
 * Otherwise it follows POSIX semantics: $VISUAL is a GUI editor (launched directly),
 * $EDITOR is a terminal editor (opened inside the configured terminal).
 * The config "editor" field is treated as VISUAL (GUI) for backward compatibility.
 */
export function OpenInEditor(cwd: string, agent: string): $CancellablePromise<void> {
    return $Call.ByID(2149184312, cwd, agent);
}

/**
 * OpenReleases opens the GitHub releases page in the system browser.
 */
export function OpenReleases(): $CancellablePromise<void> {
    return $Call.ByID(2731872152);
}

/**
 * Refresh forces a session reload. Bound to the toolbar refresh button and
 * the View menu.
 */
export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(310175433);
}

/**
 * ResumeInTerminal opens a new terminal window in the session's working
 * directory running either the normal or agent-specific YOLO resume command.
 */
export function ResumeInTerminal(sessionID: string, yolo: boolean): $CancellablePromise<void> {
    return $Call.ByID(1408127766, sessionID, yolo);
}

/**
 * SaveSettings persists the GUI-editable settings. Exclude filters apply
 * immediately; agent toggles take effect at the next launch (the session
 * provider is built at startup).
 */
export function SaveSettings(st: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(848560626, st);
}

/**
 * SetAPIPassphrase sets — or, with an empty string, clears — the API
 * passphrase, ensuring a salt exists. A running --api server picks the
 * change up at its next restart.
 */
export function SetAPIPassphrase(p: string): $CancellablePromise<void> {
    return $Call.ByID(1598448106, p);
}

/**
 * SetActivityFilter sets the activity filter.
 */
export function SetActivityFilter(f: string): $CancellablePromise<void> {
    return $Call.ByID(3837448025, f);
}

/**
 * SetCardDensity persists the desktop card density choice.
 * core.UpdateConfig holds a file lock for the whole read-modify-write, so
 * concurrent writers (this process or another lazyagent process) cannot
 * clobber each other's config fields.
 */
export function SetCardDensity(d: string): $CancellablePromise<void> {
    return $Call.ByID(2444020248, d);
}

/**
 * SetDetailWidth persists the desktop detail-panel width. Unlike the
 * density setter it clamps instead of rejecting: the value comes from a
 * drag gesture, not typed input.
 */
export function SetDetailWidth(w: number): $CancellablePromise<void> {
    return $Call.ByID(3280861733, w);
}

/**
 * SetSearchQuery sets the search query.
 */
export function SetSearchQuery(q: string): $CancellablePromise<void> {
    return $Call.ByID(3971927958, q);
}

/**
 * SetSessionName stores a custom name for a session. Empty name resets it.
 */
export function SetSessionName(sessionID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3660716453, sessionID, name);
}

/**
 * SetWindowMinutes updates the time window.
 */
export function SetWindowMinutes(m: number): $CancellablePromise<void> {
    return $Call.ByID(75887259, m);
}

/**
 * TogglePin toggles always-on-top for the detached window.
 */
export function TogglePin(): $CancellablePromise<void> {
    return $Call.ByID(2605085233);
}

// Private type creation functions
const $$createType0 = core$0.Config.createFrom;
const $$createType1 = limits$0.View.createFrom;
const $$createType2 = $models.SessionFull.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.SessionItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Settings.createFrom;
