// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the Go service exposed to the Svelte frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Attach switches from detached window back to tray panel mode.
 */
export function Attach(): $CancellablePromise<void> {
    return $Call.ByID(770700779);
}

/**
 * Detach switches from tray panel to a normal detached window.
 */
export function Detach(): $CancellablePromise<void> {
    return $Call.ByID(3825720405);
}

/**
 * GetActiveCount returns the number of sessions with active work.
 */
export function GetActiveCount(): $CancellablePromise<number> {
    return $Call.ByID(1984306295);
}

/**
 * GetConfig returns the current config.
 */
export function GetConfig(): $CancellablePromise<core$0.Config> {
    return $Call.ByID(1670992424).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSessionDetail returns full detail for a session.
 */
export function GetSessionDetail(id: string): $CancellablePromise<$models.SessionFull | null> {
    return $Call.ByID(378650659, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSessionName returns the custom name for a session.
 */
export function GetSessionName(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(190900857, sessionID);
}

/**
 * GetSessions returns all visible sessions for the list view.
 */
export function GetSessions(): $CancellablePromise<$models.SessionItem[]> {
    return $Call.ByID(330309427).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetUpdateVersion returns the newer version available, or empty if up-to-date.
 */
export function GetUpdateVersion(): $CancellablePromise<string> {
    return $Call.ByID(707030249);
}

/**
 * GetWindowMinutes returns the current time window in minutes.
 */
export function GetWindowMinutes(): $CancellablePromise<number> {
    return $Call.ByID(4178116159);
}

/**
 * IsDetached returns whether the app is currently in detached window mode.
 */
export function IsDetached(): $CancellablePromise<boolean> {
    return $Call.ByID(279822792);
}

/**
 * IsPinned returns whether the detached window is always on top.
 */
export function IsPinned(): $CancellablePromise<boolean> {
    return $Call.ByID(3827525600);
}

/**
 * OpenInEditor opens a directory in the user's editor.
 * For Cursor sessions, it opens Cursor IDE directly.
 * Otherwise it follows POSIX semantics: $VISUAL is a GUI editor (launched directly),
 * $EDITOR is a terminal editor (opened inside a Terminal.app window).
 * The config "editor" field is treated as VISUAL (GUI) for backward compatibility.
 */
export function OpenInEditor(cwd: string, agent: string): $CancellablePromise<void> {
    return $Call.ByID(2149184312, cwd, agent);
}

/**
 * OpenReleases opens the GitHub releases page in the system browser.
 */
export function OpenReleases(): $CancellablePromise<void> {
    return $Call.ByID(2731872152);
}

/**
 * SetActivityFilter sets the activity filter.
 */
export function SetActivityFilter(f: string): $CancellablePromise<void> {
    return $Call.ByID(3837448025, f);
}

/**
 * SetSearchQuery sets the search query.
 */
export function SetSearchQuery(q: string): $CancellablePromise<void> {
    return $Call.ByID(3971927958, q);
}

/**
 * SetSessionName stores a custom name for a session. Empty name resets it.
 */
export function SetSessionName(sessionID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3660716453, sessionID, name);
}

/**
 * SetWindowMinutes updates the time window.
 */
export function SetWindowMinutes(m: number): $CancellablePromise<void> {
    return $Call.ByID(75887259, m);
}

/**
 * TogglePin toggles always-on-top for the detached window.
 */
export function TogglePin(): $CancellablePromise<void> {
    return $Call.ByID(2605085233);
}

// Private type creation functions
const $$createType0 = core$0.Config.createFrom;
const $$createType1 = $models.SessionFull.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.SessionItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
